name: push feat

on:
  pull_request:
    types: [closed]

jobs:
  pull-request-close:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}
          echo "push ts"

      - name: Print the current time
        run: |
          echo $(date)