name: Runner

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        name
        version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
        
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      
			- name: Unit Tests
			  run: |
				  npm install
				  npm test
      